### PR TITLE
added timestamp for cachebusting

### PR DESCRIPTION
**Pull request by lzl124631x**
something like this

```
@font-face {
    font-family: "<%= fontName %>";
    src: url('<%= fontPath %><%= fontName %>.eot?t=<%= timestamp %>');
    src: url('<%= fontPath %><%= fontName %>.eot?t=<%= timestamp %>#iefix') format('eot'),
        url('<%= fontPath %><%= fontName %>.woff2?t=<%= timestamp %>') format('woff2'),
        url('<%= fontPath %><%= fontName %>.woff?t=<%= timestamp %>') format('woff'),
        url('<%= fontPath %><%= fontName %>.ttf?t=<%= timestamp %>') format('truetype'),
        url('<%= fontPath %><%= fontName %>.svg?t=<%= timestamp %>#<%= fontName %>') format('svg');
}
```

### CODE REVIEW

**Comment by backflip** [comment]
Sounds good, thanks!
Could you please use `null` as a default value and wrap `?t=<%= timestamp %>` with `<% if (timestamp) { %>…<% } %>`?

**Comment by lzl124631x** [comment]
@backflip Thanks for your review. The `<%= timestamp %>` is in the css template file provided by user, which means that it is the user's choice of whether or not to insert the timestamp to css file. So, user might do something other than
> wrap `?t=<%= timestamp %>` with `<% if (timestamp) { %>…<% } %>`

I mean, it's not under my control.

Speaking of the default value, I had a look into the source of `gulp-iconfont` -- the `timestamp` argument is passed to `gulp-svg2ttf`. And in `gulp-svg2ttf`, there is

>**options.timestamp**
Type: `Number` Default value: `Math.round(Date.now()/1000)`
Override the TTF font creation/modification date.

So, I propose to use the same type (`Number`) and default value (`Math.round(Date.now()/1000)`) for this `timestamp` setting in `gulp-iconfont-css` so that the behaviors across these highly-related tool-kits are **consistent**. What do you think?

**Comment by lzl124631x** [comment]
Hi @backflip  still there?

**Comment by ashconnell** [comment]
+1 can we get this merged?

**Comment by ashconnell** [comment]
FYI i just noticed you can use `<%= _.now() %>` in your templates if you're using lodash templating.

**Comment by jefsnare** [comment]
@lzl124631x I like the idea of https://github.com/backflip/gulp-iconfont-css/pull/42 more than this PR. With the other PR it's possible to configure the best cache bust option for you available.

**Pull request closed without merging**
