### PR TITLE
remove peer dependencies

### LINKED ISSUE #29: peerDependencies issues
Hi guys,

I've been running into this issue when I try to install gulp-iconfont-css and gulp-icon-font

```
npm WARN peerDependencies The peer dependency gulp-iconfont@~4.0.0 included from gulp-iconfont-css will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency mongodb@~1.4 included from mongoskin will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
```

Any thoughts on this?

Thanks!

### PR DESCRIPTION
**Pull request by nfriedly**
Alternative to #31, also fixes #29

### CODE REVIEW

**Comment by backflip** [comment]
@nfroidure Since peer dependencies do not exist anymore: Would you specify `gulp-iconfont` as a "real" dependency?

**Comment by nfriedly** [comment]
I think people will have to keep it as a separate dependency unless we make significant changes to this module to have it actually use gulp-iconfont internally.

(If the user has to `require()` it, then it has to be a top-level dependency for the current version of npm.)

**Comment by backflip** [comment]
The advantage would be that we could specify a version range which is compatible with this plugin.

**Comment by nfriedly** [comment]
Yea, its really not a bad idea, its just that its more involved than the quick-fix here.

**Comment by backflip** [comment]
Fair enough. But we need it as a `devDependencies` for the tests to run.

**Comment by nfriedly** [comment]
So, now that I'm looking at the code more closely, it might not be so hard to just pipe to gulp-iconfont internally, then we'd have it as a regular dependency and users won't even need to install it. Let me see if I can put it together today or tomorrow...

**Comment by backflip** [comment]
@nfroidure Would you be fine with adapting this plugin to use `gulp-iconfont` internally or would you rather see it being officially deprecated?

**Comment by backflip** [comment]
@nfriedly On second thought: Let's not use `gulp-iconfont` internally. A gulp plugin is supposed to do one thing only and this would kinda work against it. If you add it as a devDependency I will merge it and release a new version. Thanks for your patience. :)

**Comment by nfriedly** [comment]
Sounds good, just a minute.

**Comment by backflip** [comment]
No pressure, I will be back in about 8 hours.

**Comment by nfroidure** [comment]
Free as in freedom ;)

gulp-iconfont bundle: gulp-svgicons2svgfont gulp-svg2ttf gulp-ttf2woff gulp-ttf2woff2 etc...

I'm ok with any use of gulp-iconfont :).

**Comment by backflip** [comment]
Okay. :)

@nfriedly: Thanks again, released with 2.0.0.

**Comment by nfriedly** [comment]
Awesome, thanks!

**Pull request merged**
